#!/bin/bash

tr '\r' '\n' < ~/Downloads/Smart.m3u > ~/Downloads/Smart.d.m3u
cat ~/Downloads/Smart.d.m3u | grep -v "^#" > ~/Downloads/Smart.m3u
sed -e 's/Users\/jakubtymejczyk/mnt\/samba/g' ~/Downloads/Smart.m3u > ~/Downloads/Smart.d.m3u
/usr/bin/iconv -f UTF8-MAC -t UTF8 < ~/Downloads/Smart.d.m3u > ~/Downloads/Smart.m3u

scp ~/Downloads/Smart.m3u root@192.168.1.7:/etc/mpd/Playlists/Smart.m3u

rm ~/Downloads/Smart.m3u ~/Downloads/Smart.d.m3u
