#!/bin/bash

##################################LICENSE#######################################
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


USER="root"
ADDRESS="192.168.1.7"
PATHREMOTE="/etc/mpd/Playlists"
PATHLOCAL="/Users/jakubtymejczyk/Downloads"
PLAYLIST="Smart.m3u8"
SEDLOCAL="Users\/jakubtymejczyk"
SEDREMOTE="mnt\/samba"

tr '\r' '\n' < "$PATHLOCAL/$PLAYLIST" > "$PATHLOCAL/$PLAYLIST.tmp"
cat "$PATHLOCAL/$PLAYLIST.tmp" | grep -v "^#" > "$PATHLOCAL/$PLAYLIST"
sed -e 's/'$SEDLOCAL'/'$SEDREMOTE'/g' "$PATHLOCAL/$PLAYLIST" > \
	"$PATHLOCAL/$PLAYLIST.tmp"
/usr/bin/iconv -f UTF8-MAC -t UTF8 < "$PATHLOCAL/$PLAYLIST.tmp" \
	> "$PATHLOCAL/$PLAYLIST"

scp "$PATHLOCAL/$PLAYLIST" "$USER@$ADDRESS:$PATHREMOTE"

rm "$PATHLOCAL/$PLAYLIST" "$PATHLOCAL/$PLAYLIST.tmp"
