#!/bin/bash

###################################USAGE########################################
#/path/to/script "path to dap"
################################################################################

###################################LICENSE######################################
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

###################################VARIABLES####################################
#Variables
MUSICDIR="/Users/jakubtymejczyk/Music/iTunes/iTunes Media/Music"
#COVERDIR="/Users/jakubtymejczyk/Music/Covers"
DAPDIR=
PLAYLIST="Galaxy.txt"
WIDTH2=80
BITRATE=4
CONVERT=0
FOLDER=0

#Extra variables - do NOT touch
MUSICDIRL=${#MUSICDIR}
let MUSICDIRL=$MUSICDIRL+5
let WIDTH3=$WIDTH2-2
let CUT1=$WIDTH2-18
let CUT2=$CUT1-3
################################################################################

###################################FUNCTIONS####################################
#Leading zeros
function leadingzeros {
printf "%03d" $1
}

#progress
function progress {
PERCENT=$1
WIDTH=$2

let WIDTH=$WIDTH-1
let PRZED=($PERCENT*$WIDTH)/100
let PO=$WIDTH-$PRZED-2

bar="["

if [ $PRZED -gt 0 ]; then
	for i in $(eval echo {0..$PRZED}); do
		bar="$bar="
	done
else
	let PO=$PO+1
fi

if [ $PRZED -ne $WIDTH ]; then
	bar="$bar>"
fi

if [ $PO = 0 ]; then
	bar="$bar-"
fi

if [ $PO -gt 0 ]; then
	for i in $(eval echo {0..$PO}); do
		bar="$bar-" 
	done
fi

bar="$bar]"

echo "$bar"
}

trap ctrl_c INT
function ctrl_c() {
mv "$DAPDIR/$PLAYLIST.bak" "$DAPDIR/$PLAYLIST"
exit 1
}
################################################################################

###################################STEP -1: Options#############################
while getopts "hp:P:cfb:" OPTION
do
case $OPTION in
	h)
		echo "syncanymp3with iTunes
Usage:
$0
-p pathtodap
-P playlist
-c convert [true]
-f covers [true]
-b bitrate [0..9]"
		exit 1
		;;
	p)
		DAPDIR="$OPTARG"
		;;
	P)
		PLAYLIST="$OPTARG"
		;;
	f)
		FOLDER="1"
		;;
	c)
		CONVERT="$OPTARG"
		;;
	b)
		BITRATE="$OPTARG"
		;;
	?)
		usage
		exit
		;;
	esac
done

################################################################################

###################################STEP 0: Exists?##############################
if [ ! -f "$DAPDIR/$PLAYLIST" -o ! -d "$DAPDIR" -o ! -d "$MUSICDIR" ]; then
echo "Check variables or connect DAP.
Exit"
exit 1
fi
################################################################################

###################################STEP 0.5: Values#############################
echo "syncanymp3withitunes
Values:
Local path: $MUSICDIR
Covers path: $COVERDIR
DAP path: $DAPDIR
Playlist: $PLAYLIST
Convert: $CONVERT"
if [ $CONVERT = 1 ]; then
	echo "Bitrate: V$BITRATE"
fi
echo "-------------------------------"
################################################################################

###################################STEP 1: Convert playlist#####################
cp "$DAPDIR/$PLAYLIST" "$DAPDIR/$PLAYLIST.bak"
iconv -c -f UTF-16LE -t UTF-8 "$DAPDIR/$PLAYLIST" > "$DAPDIR/$PLAYLIST.work"
mv "$DAPDIR/$PLAYLIST.work" "$DAPDIR/$PLAYLIST"
tr '\r' '\n' < "$DAPDIR/$PLAYLIST" > "$DAPDIR/$PLAYLIST.work"
mv "$DAPDIR/$PLAYLIST.work" "$DAPDIR/$PLAYLIST"
################################################################################

###################################STEP 2: Get filenames########################
#On playlist
awk -F'\t' '{ print $27 }' "$DAPDIR/$PLAYLIST" | cut -c$MUSICDIRL- | \
	sed -e '1d' -e '/^$/ d' | sort > /tmp/sync.1

#On DAP
find "$DAPDIR" -type f -name "*.mp3" | sort | \
	sed -e 's:'"$DAPDIR"'/::g' -e 's/\//:/g' > /tmp/sync.2
################################################################################

###################################STEP 3: Differences##########################
diff /tmp/sync.1 /tmp/sync.2 > /tmp/sync.3
################################################################################

###################################STEP 4: Deleting#############################
grep ">" /tmp/sync.3 | sed -e 's/> //g' > /tmp/sync.4
I=1
ILE=`cat /tmp/sync.4 | wc -l | sed -e 's/ //g'`

if [ $ILE = 0 ]; then
	echo -ne "Nothing to delete\r"
fi

ILE=`leadingzeros $ILE`

cat /tmp/sync.4 | while read f; do
	g=`echo "$f" | sed -e 's/\:/\//g'`
	h=`echo "$f" | sed -e 's/\.mp3//g'`
	LENGTH=${#h}
	if [ $LENGTH -gt $CUT1 ]; then
		h=`echo "$h" | cut -c-$CUT2`
		h="$h..."
	else
		let diff=$CUT1-$LENGTH
		while [ $diff -gt 0 ]; do
			h="$h."
			let diff--
		done
	fi
	let PERCENT=($I*100)/$ILE
	PERCENT=`leadingzeros $PERCENT`
	IE=`leadingzeros $I`
	echo "$IE/$ILE ($PERCENT%): < $h"
	rm "$DAPDIR/$g"
	let I++
done
################################################################################

echo ""

###################################STEP 5: Sizes and copying####################
grep "<" /tmp/sync.3 | sed -e 's/< //g' > /tmp/sync.4

I=1
ILE=`wc -l /tmp/sync.4 | sed -e 's/ //g' -e 's/\/tmp\/sync.4//g'`

if [ $ILE = 0 ]; then
	echo -ne "Nothing to copy\r"
fi

ILE=`leadingzeros $ILE`

#Get sizes of files
SIZE=0
while read f; do
	g=`echo $f | sed -e 's/\:/\//g'`
	FILESIZE=`du -k "$MUSICDIR/$g" | awk '{ print $1 }'`
	let SIZE=$SIZE+$FILESIZE
	SIZES="$SIZES
$FILESIZE"
done < /tmp/sync.4

echo "$SIZES" | sed -e '1d' > /tmp/sync.sizes

while read f; do
	g=`echo "$f" | sed -e 's/\:/\//g'`
	h=`echo "$f" | sed -e 's/.mp3//g'`
	DISC=1
	ARTIST=`echo "$h" | awk -F \: '{ print $1}' | \
		/opt/local/bin/iconv -f utf-8 -t ascii//translit//ignore`
	ALBUM=`echo "$h" | awk -F \: '{ print $2}' | \
		/opt/local/bin/iconv -f utf-8 -t ascii//translit//ignore`
	TRACK=`echo "$h" | awk -F \: '{ print $3}' | awk -F " " '{ print $1}'`
	TEST=`echo "$TRACK" | sed 's/^[0-9-]*//' | wc -c`
	if [ $TEST -ne 1 ]; then
		TITLE=`echo "$h" | awk -F \: '{ print $3}'`
		TRACK=""
	else
		TITLE=`echo "$h" | awk -F \: '{ print $3}' | cut -c4- | \
			/opt/local/bin/iconv -f utf-8 -t ascii//translit//ignore`
		if [ `echo "$TRACK" | grep "-" | wc -l` -eq 1 ]; then
			TITLE=`echo "$h" | awk -F \: '{ print $3}' | cut -c6- | \
				/opt/local/bin/iconv -f utf-8 -t ascii//translit//ignore`
			TRACK=`echo "$h" | awk -F \: '{ print $3}' | \
				awk -F " " '{ print $1}' | \
				awk -F "-" '{ print $2}'`
			DISC=`echo "$h" | awk -F \: '{ print $3}' | \
				awk -F " " '{ print $1}' | \
				awk -F "-" '{ print $1}'`
		fi
	fi
	#echo "$h"
	#echo "$TITLE" : "$TRACK" : "$ALBUM" : "$ARTIST"
	LENGTH=${#h}
	if [ $LENGTH -gt $CUT1 ]; then
		h=`echo "$h" | cut -c-$CUT2`
		h="$h..."
	else
		let diff=$CUT1-$LENGTH
		while [ $diff -gt 0 ]; do
			h="$h."
			let diff--
		done
	fi
	ACSIZE=`sed -n ''$I'p' /tmp/sync.sizes`
	let PROGRESS=$PROGRESS+$ACSIZE
	let PERCENT=($PROGRESS*100)/$SIZE
	PERCENTE=`leadingzeros $PERCENT`
	IE=`leadingzeros $I`
	bar2=`progress $PERCENT $WIDTH3`
	echo -ne "$IE/$ILE ($PERCENTE%): > $h
$bar2\r"
	MP3DIR=`echo "$g" | awk -F'/' '{ print $1"/"$2 }'`
	if [ ! -d "$DAPDIR/$MP3DIR" ]; then
		mkdir -p "$DAPDIR/$MP3DIR"
		if [ $FOLDER -eq 1 ]; then
			if [ -f "$MUSICDIR/$MP3DIR/"*".png" ]; then
				cp "$MUSICDIR/$MP3DIR/"*".png" "$DAPDIR/$MP3DIR/cover.png"
			fi
		fi
	fi
	if [ $CONVERT -eq 1 ] ; then
		cp "$MUSICDIR/$g" "/tmp/$f"
		lame --quiet -V$BITRATE "/tmp/$f" "/tmp/$f-low"
		eyeD3 -a "$ARTIST" -A "$ALBUM" -t "$TITLE" -n "$TRACK" \
			--set-text-frame=TPOS:$DISC \
			--add-image="$DAPDIR/$MP3DIR/cover.png:FRONT_COVER" \
			"/tmp/$f-low" \
			&> /dev/null
		cp "/tmp/$f-low" "$DAPDIR/$g"
		rm "/tmp/$f" "/tmp/$f-low"
	else
		cp "$MUSICDIR/$g" "$DAPDIR/$g"
		if [ -f "$DAPDIR/$MP3DIR/cover.png" ]; then
			eyeD3 --remove-all -a "$ARTIST" -A "$ALBUM" -t "$TITLE" -n "$TRACK" \
				--set-text-frame=TPOS:$DISC \
				--add-image="$DAPDIR/$MP3DIR/cover.png:FRONT_COVER" \
				"$DAPDIR/$g" \
				&> /dev/null
		else
			eyeD3 --remove-all -a "$ARTIST" -A "$ALBUM" -t "$TITLE" -n "$TRACK" \
 				--set-text-frame=TPOS:$DISC \
				"$DAPDIR/$g" \
				&> /dev/null
		fi
	fi
	let I++
done < /tmp/sync.4
################################################################################

###################################STEP 6: Ending###############################
echo "
Removing temp files and restore playlist"
mv "$DAPDIR/$PLAYLIST.bak" "$DAPDIR/$PLAYLIST"
rm /tmp/sync*
#rm "$DAPDIR/._"*
find "$DAPDIR" -mindepth 2 -maxdepth 2  -type d -exec \
	sh -c 'set -- "$0"/*.mp3; ! [ -e "$1" ]' {} \;  -exec rm -rf {} \;
#/Artist/Album. Even if album is empty, artist isn't. So check for empty aritsts
find "$DAPDIR" -mindepth 1 -maxdepth 1 -type d -empty -exec rm -rf {} \;
################################################################################

###################################AUTHOR: Jakub Tymejczyk######################
